### ISSUE TITLE
This working?

### ISSUE THREAD

**Issue by RoccoZero** [valinet/NewOutlookPatcher#10]

**Comment by RoccoZero** [comment]
![image](https://github.com/valinet/NewOutlookPatcher/assets/33149580/3c3e83a6-9cd4-42e1-83f7-f6310c2e953b)

**Comment by valinet** [comment]
Check out latest version, that should be fixed: https://github.com/valinet/NewOutlookPatcher/releases/tag/2024.06.24.01

**Comment by RoccoZero** [comment]
> Check out latest version, that should be fixed: https://github.com/valinet/NewOutlookPatcher/releases/tag/2024.06.24.01

Thanks, working!
