### ISSUE TITLE
Ads are only hidden in "Focus" mode

### ISSUE THREAD

**Issue by Znuff** [valinet/NewOutlookPatcher#11]
Per title, when setting the Inbox layout to "Don't sort my messages", the Ads still show up:

![image](https://github.com/valinet/NewOutlookPatcher/assets/496793/1af73125-8031-4535-a06e-cb38f206de14)

When setting it to "Focus", the ads are properly hidden:

![image](https://github.com/valinet/NewOutlookPatcher/assets/496793/40a6e8c0-eb07-4de0-8724-4c25aa6e3070)

> You have Microsoft Outlook Version 1.2024.605.100 (Production).
> Client Version is 20240531006.12 .
> WebView2 Version is 125.0.2535.92 .

**Comment by valinet** [comment]
Is it still happening with the latest version: https://github.com/valinet/NewOutlookPatcher/releases/tag/2024.06.24.01 ?

**Comment by Znuff** [comment]
It shows up for a brief second, but then it gets hidden. 

---

Slightly related: if you *do* opt for the sort into Focused and Others, the "Others" tab still has ads:

![image](https://github.com/valinet/NewOutlookPatcher/assets/496793/03edbbf6-d129-4c24-bd81-e1bf007d3079)

**Comment by valinet** [comment]
> It shows up for a brief second, but then it gets hidden.

Yeah, that's the expected/observed behavior on my end as well. It is fine. Probably that is some other element that's show as a placeholder before the "proper" ad loads. If we catch its id/signature, we can hide that as well, problem is it is hard to have the inspector open in time to be able to catch it. Investigating... For now, it generally works.

> Slightly related: if you do opt for the sort into Focused and Others, the "Others" tab still has ads:

Thanks, I fixed it in [2024.06.24.02](https://github.com/valinet/NewOutlookPatcher/releases/tag/2024.06.24.01).

**Comment by valinet** [comment]
> It shows up for a brief second, but then it gets hidden.

Should be fixed in [2024.06.24.03](https://github.com/valinet/NewOutlookPatcher/releases/tag/2024.06.24.01).
