### ISSUE TITLE
Thanks Val!

### ISSUE THREAD

**Issue by bbmaster123** [valinet/NewOutlookPatcher#7]
Hey man, hope you're well :)
Thanks for the patcher, working well for me on my 22631.3447 build!
I seem to have to run it a few times for it to hook or whatever its doing, but it does work

I read the readme and only just briefly skimmed the code, but maaaaan that looks like it must've been a lot of work! 5 sub projects!

Yea the WindowsApps folder is hard to deal with in userspace. The only way I found to be able to tinker with anything was to allow loose windows apps on my D:\ drive, which is fine for testing but isn't great for an actual release

Anyway just wanted to stop by and say hi and thank you :)

**Comment by valinet** [comment]
Yeah, indeed it is a pain. Basically, a TON of the code is just dealing with that. I will look into migrating this to a better solution; maybe using the `AppVerifier` infrastructure, or as a Windhawk mod...

Good to be talking with you after so much time, I hope you're doing well and wish you all the best.

**Comment by valinet** [comment]
Check out the new version, I have improved basically the entire architecture, should be more steamlined now: https://github.com/valinet/NewOutlookPatcher/releases/tag/2024.06.24.01

**Comment by bbmaster123** [comment]
Nice to hear back from you, thanks for the well wishes :)
I checked out the new release this morning, worked perfect first try! Seemed a bit faster overall as well!

Looks like they had changed the css selector ID's again, they do that every few months on the web version of outlook too. Did you copy the new ID's from the web version or does the outlook app have its own? Just curious.

Thanks again man, best wishes to you too <3
