### ISSUE TITLE
Crashes with "An attempt was made to write to read-only memory" BSOD error

### ISSUE THREAD

**Issue by lennon1997** [valinet/NewOutlookPatcher#8]
After asking for admin privileges the computer crashes and no changes are made to outlook. Mentions RTcore64.sys
I have disabled core isolation settings; any advice on how to proceed?

**Comment by avi-cenna** [comment]
I got the same error. I did not do anything to disable "core isolation" settings though...

**Comment by valinet** [comment]
Try latest version, should be fixed now: https://github.com/valinet/NewOutlookPatcher/releases/tag/2024.06.24.01
